// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpwvwcefvljdjfdnhkmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwd3Z3Y2VmdmxqZGpmZG5oa21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzM5NzUsImV4cCI6MjA3MDMwOTk3NX0.tgrq5jxMDI6pNT5j52CWrk3Jt_CJnyEJhmzlHdSYr0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});